export const IPC_CHANNELS = {
  COMFYUI_CONNECT: 'comfyui:connect',
  COMFYUI_DISCONNECT: 'comfyui:disconnect',
  COMFYUI_STATUS: 'comfyui:status',
  COMFYUI_SYSTEM_STATS: 'comfyui:system-stats',
  COMFYUI_MODELS: 'comfyui:models',

  WORKFLOW_IMPORT: 'workflow:import',
  WORKFLOW_LIST: 'workflow:list',
  WORKFLOW_GET: 'workflow:get',
  WORKFLOW_DELETE: 'workflow:delete',
  WORKFLOW_UPDATE: 'workflow:update',
  WORKFLOW_VARIABLES: 'workflow:variables',
  WORKFLOW_SET_VARIABLES: 'workflow:set-variables',
  WORKFLOW_UPDATE_VARIABLE_ROLE: 'workflow:update-variable-role',
  WORKFLOW_UPDATE_VARIABLE_VALUE: 'workflow:update-variable-value',

  MODULE_LIST: 'module:list',
  MODULE_GET: 'module:get',
  MODULE_CREATE: 'module:create',
  MODULE_UPDATE: 'module:update',
  MODULE_DELETE: 'module:delete',
  MODULE_EXPORT: 'module:export',
  MODULE_IMPORT_DATA: 'module:import-data',

  MODULE_ITEM_LIST: 'module-item:list',
  MODULE_ITEM_CREATE: 'module-item:create',
  MODULE_ITEM_UPDATE: 'module-item:update',
  MODULE_ITEM_DELETE: 'module-item:delete',
  MODULE_ITEM_REORDER: 'module-item:reorder',

  CHARACTER_LIST: 'character:list',
  CHARACTER_GET: 'character:get',
  CHARACTER_CREATE: 'character:create',
  CHARACTER_UPDATE: 'character:update',
  CHARACTER_DELETE: 'character:delete',

  BATCH_CREATE: 'batch:create',
  BATCH_LIST: 'batch:list',
  BATCH_GET: 'batch:get',
  BATCH_START: 'batch:start',
  BATCH_PAUSE: 'batch:pause',
  BATCH_RESUME: 'batch:resume',
  BATCH_CANCEL: 'batch:cancel',
  BATCH_DELETE: 'batch:delete',
  BATCH_RERUN: 'batch:rerun',
  BATCH_REORDER: 'batch:reorder',
  BATCH_DELETE_TASKS: 'batch:delete-tasks',
  BATCH_PREVIEW_COUNT: 'batch:preview-count',
  BATCH_TASKS: 'batch:tasks',
  QUEUE_STATUS: 'queue:status',

  GALLERY_LIST: 'gallery:list',
  GALLERY_GET: 'gallery:get',
  GALLERY_RATE: 'gallery:rate',
  GALLERY_FAVORITE: 'gallery:favorite',
  GALLERY_DELETE: 'gallery:delete',
  GALLERY_EXPORT: 'gallery:export',
  GALLERY_COPY_CLIPBOARD: 'gallery:copy-clipboard',
  GALLERY_SHOW_IN_EXPLORER: 'gallery:show-in-explorer',

  PROMPT_PREVIEW: 'prompt:preview',
  DASHBOARD_STATS: 'dashboard:stats',

  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SETTINGS_GET_ALL: 'settings:getAll',

  DIALOG_OPEN_FILE: 'dialog:open-file',
  DIALOG_OPEN_DIRECTORY: 'dialog:open-directory',

  TERMINAL_CREATE: 'terminal:create',
  TERMINAL_INPUT: 'terminal:input',
  TERMINAL_RESIZE: 'terminal:resize',
  TERMINAL_DESTROY: 'terminal:destroy',
  TERMINAL_DATA: 'terminal:data',
  TERMINAL_EXIT: 'terminal:exit',

  MCP_START: 'mcp:start',
  MCP_STOP: 'mcp:stop',
  MCP_STATUS: 'mcp:status',
  MCP_CONFIG_STATUS: 'mcp:config-status',
  MCP_SETUP_CLI: 'mcp:setup-cli',
  MCP_REMOVE_CLI: 'mcp:remove-cli',

  QUEUE_PROGRESS: 'queue:progress',
  QUEUE_TASK_COMPLETED: 'queue:task-completed',
  QUEUE_TASK_FAILED: 'queue:task-failed',
  QUEUE_JOB_COMPLETED: 'queue:job-completed',
  QUEUE_STATUS_CHANGED: 'queue:status-changed',
  COMFYUI_CONNECTION_CHANGED: 'comfyui:connection-changed',
  COMFYUI_PREVIEW: 'comfyui:preview'
} as const
